# This file was generated by the {rix} R package v0.15.0 on 2025-02-12
# with following call:
# >rix(date = "2025-01-14",
#  > r_pkgs = c("tibble",
#  > "lubridate",
#  > "stringr",
#  > "dplyr",
#  > "clock",
#  > "httr2",
#  > "jsonlite",
#  > "openxlsx2",
#  > "fs",
#  > "dbplyr",
#  > "shiny",
#  > "toastui",
#  > "pool",
#  > "bslib",
#  > "reactable",
#  > "DT",
#  > "golem",
#  > "devtools",
#  > "dockerfiler",
#  > "renv",
#  > "connectapi",
#  > "auth0",
#  > "attachment",
#  > "testthat",
#  > "slackr",
#  > "markdown"),
#  > system_pkgs = c("dolt", "flyctl),
#  > git_pkgs = list(list(package_name = "doltr",
#  > repo_url = "https://github.com/ecohealthalliance/doltr/",
#  > commit = "ffb5bc68003e83ebdb9f352654bab2515ca6bf3a"),
#  >      list(package_name = "shinyslack",
#  > repo_url = "https://github.com/r4ds/shinyslack",
#  > commit = "c52d08d1ca59496785b7beee6a6a6ad99fa9bc38")),
#  > ide = "none",
#  > project_path = getwd(),
#  > overwrite = TRUE,
#  > r_ver = "4.4.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-01-14.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      attachment
      auth0
      bslib
      clock
      connectapi
      dbplyr
      devtools
      dockerfiler
      dplyr
      DT
      fs
      golem
      httr2
      jsonlite
      lubridate
      markdown
      openxlsx2
      pool
      reactable
      renv
      shiny
      slackr
      stringr
      testthat
      tibble
      toastui;
  };
 
    doltr = (pkgs.rPackages.buildRPackage {
      name = "doltr";
      src = pkgs.fetchgit {
        url = "https://github.com/ecohealthalliance/doltr/";
        rev = "ffb5bc68003e83ebdb9f352654bab2515ca6bf3a";
        sha256 = "sha256-jO+6VsY4Dmk25uk1ytz0qAlH0Vt9gTm34o6ymYW2PLg=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          blob
          cli
          DBI
          dbplyr
          dbx
          dplyr
          httpuv
          jsonlite
          processx
          ps
          rlang
          RMariaDB
          R_utils
          rstudioapi;
      };
    });


    scenes = (pkgs.rPackages.buildRPackage {
      name = "scenes";
      src = pkgs.fetchgit {
        url = "https://github.com/shinyworks/scenes";
        rev = "8c56263c34b631b0df520f277c28d45d0c27c5c0";
        sha256 = "sha256-7/Ii0ni4mU3ao+ylVLcdn5MbAFBbVurfdbAhKA2X7Mw=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          cli
          cookies
          glue
          purrr
          rlang
          shiny;
      };
    });


    slackcalls = (pkgs.rPackages.buildRPackage {
      name = "slackcalls";
      src = pkgs.fetchgit {
        url = "https://github.com/yonicd/slackcalls";
        rev = "f8fa05e4b92f3deea0b298ee09bcd2ebb2ae880a";
        sha256 = "sha256-hMBCXQddWkUxW1T8LHw2cA3NfTCikC87fjTCTou8Aw8=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          httr;
      };
    });

    slackteams = (pkgs.rPackages.buildRPackage {
      name = "slackteams";
      src = pkgs.fetchgit {
        url = "https://github.com/yonicd/slackteams";
        rev = "a15993c5849b986f0759c6082b6d751fe31d9b9d";
        sha256 = "sha256-q99ucggp2W1XNLCFIkjr0PwynYkdjmjTcElfRQuYCbg=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          httr
          jsonlite
          data_table
          tibble
          yaml;
      } ++ [ slackcalls ];
    });

    shinyslack = (pkgs.rPackages.buildRPackage {
      name = "shinyslack";
      src = pkgs.fetchgit {
        url = "https://github.com/r4ds/shinyslack";
        rev = "c52d08d1ca59496785b7beee6a6a6ad99fa9bc38";
        sha256 = "sha256-ArxGEp8DWBwrFkZtOL1OhsTLi/kxoyyrB7UknRW+RMA=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          cli
          cookies
          httr
          rlang
          shiny
          sodium;
      } ++ [ scenes slackcalls slackteams ];
    });
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      dolt
      flyctl
      glibcLocales
      nix
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [ doltr shinyslack rpkgs  system_packages   ];
  
}
