# This file was generated by the {rix} R package v0.15.8 on 2025-04-02
# with following call:
# >rix(date = "2025-01-14",
#  > r_pkgs = c("tibble",
#  > "lubridate",
#  > "stringr",
#  > "dplyr",
#  > "clock",
#  > "httr2",
#  > "jsonlite",
#  > "openxlsx2",
#  > "fs",
#  > "dbplyr",
#  > "shiny",
#  > "toastui",
#  > "pool",
#  > "bslib",
#  > "reactable",
#  > "DT",
#  > "golem",
#  > "devtools",
#  > "dockerfiler",
#  > "renv",
#  > "auth0",
#  > "attachment",
#  > "testthat",
#  > "slackr",
#  > "markdown",
#  > "dotenv"),
#  > system_pkgs = c("dolt",
#  > "flyctl"),
#  > git_pkgs = list(list(package_name = "doltr",
#  > repo_url = "https://github.com/ecohealthalliance/doltr/",
#  > commit = "ffb5bc68003e83ebdb9f352654bab2515ca6bf3a")),
#  > local_r_pkgs = local_r_pkgs,
#  >      ide = "none",
#  > project_path = getwd(),
#  > overwrite = TRUE,
#  > r_ver = "4.4.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-01-14.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      attachment
      auth0
      bslib
      clock
      dbplyr
      devtools
      dockerfiler
      dotenv
      dplyr
      DT
      fs
      golem
      httr2
      jsonlite
      lubridate
      markdown
      openxlsx2
      pool
      reactable
      renv
      shiny
      slackr
      stringr
      testthat
      tibble
      toastui;
  };
 
    doltr = (pkgs.rPackages.buildRPackage {
      name = "doltr";
      src = pkgs.fetchgit {
        url = "https://github.com/ecohealthalliance/doltr/";
        rev = "ffb5bc68003e83ebdb9f352654bab2515ca6bf3a";
        sha256 = "sha256-jO+6VsY4Dmk25uk1ytz0qAlH0Vt9gTm34o6ymYW2PLg=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          blob
          cli
          DBI
          dbplyr
          dbx
          dplyr
          httpuv
          jsonlite
          processx
          ps
          rlang
          RMariaDB
          R_utils
          rstudioapi;
      };
    });
     
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      dolt
      flyctl
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ doltr rpkgs   system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
