default:
  golem_name: calendar.admin
  golem_version: 0.0.0.9008
  app_prod: no
  dolt_local: no
  repo: rpodcast/curation-schedule
  from_owner: rpodcast
  from_repo_name: curation-schedule
  to_owner: rpodcast
  to_repo_name: curation-schedule
  to_branch: main
  slack_channel: '#random'
  notify_user: no
  port: 2557
  app_type: local
production:
  app_prod: yes
  dolt_local: no
  repo: rweekly-org/curation-schedule
  from_owner: rweekly-org
  from_repo_name: curation-schedule
  to_owner: rweekly-org
  to_repo_name: curation-schedule
  to_branch: main
  slack_channel: '#dev'
  notify_user: yes
  port: 4557
  app_type: production
staging:
  dolt_local: no
  port: 3557
  app_type: staging
dev:
  golem_wd: !expr golem::pkg_path()
