# fly.toml app configuration file generated for rph2023breakapp on 2025-02-24T19:15:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rwcaladmin'
primary_region = 'bos'

[build]
  image = 'rpodcast/calendar.admin:main'

[env]
  GOLEM_CONFIG_ACTIVE = 'production'

[http_service]
  internal_port = 2557
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  GOLEM_CONFIG_ACTIVE=production